#!/bin/bash
source ~/dotfiles/source/functions

case $(uname) in
  Linux)
    emacsclient=/usr/bin/emacsclient
    ;;
  Darwin)
    emacsclient=/usr/local/bin/emacsclient
    ;;
esac

if [ "$INSIDE_EMACS" = "vterm" ]; then
  findfile "$@"
elif [ -n "${INSIDE_EMACS+1}" ]; then
  $emacsclient -n -c "$@" # 2> /dev/null
else
  $emacsclient -n -c -q "$@"
fi
