#!/bin/bash
emacsclient=/usr/local/bin/emacsclient
if [ ! -e "$emacsclient" ]; then
  emacsclient=/usr/bin/emacsclient # linux
fi

if $INSIDE_EMACS; then
  $emacsclient -a -c emacs -q "$@"
else
  $emacsclient -a "" -t "$@" # 2> /dev/null
fi
