#!/bin/bash
emacsclient=/usr/local/bin/emacsclient
if [ ! -e "$emacsclient" ]; then
  emacsclient=/usr/bin/emacsclient # linux
fi

if [ -z $INSIDE_EMACS ]; then
  $emacsclient -a "" -t "$@" # 2> /dev/null
else
  $emacsclient -a -c -q "$@"
fi
