#!/bin/bash

# TODO torgeir is this longer needed?
case $(uname) in
  Linux)
    emacsclient=/usr/bin/emacsclient
    ;;
  Darwin)
    emacsclient=/usr/local/bin/emacsclient
    ;;
esac


if [ -n "${INSIDE_EMACS+1}" ]; then
  $emacsclient -s torgemacs -n -c "$@" # 2> /dev/null
else
  $emacsclient -s torgemacs -c -q "$@"
fi