#!/bin/bash

# TODO torgeir do you use this file?

source ~/dotfiles/source/functions

# TODO torgeir is this longer needed?
case $(uname) in
  Linux)
    emacsclient=/usr/bin/emacsclient
    ;;
  Darwin)
    emacsclient=/usr/local/bin/emacsclient
    ;;
esac


#alias eterm="/usr/local/bin/emacsclient -s torgemacs -e '(progn (select-frame-set-input-focus (selected-frame)) (+vterm/here nil))'"
#

if [ "$INSIDE_EMACS" = "vterm" ]; then
  true
elif [ -n "${INSIDE_EMACS+1}" ]; then
  $emacsclient -s torgemacs -e "(progn (select-frame-set-input-focus (selected-frame)) (let ((default-directory \"$PWD\")) (+vterm/here t)))"
  true
else
  $emacsclient -s torgemacs -e '(progn (select-frame-set-input-focus (selected-frame)) (let ((default-directory (projectile-acquire-root))) (+vterm/here t)))'
  true
fi
