#!/bin/bash
#
# Extremely simple emacsclient wrapper for item2 "Semantic History" process running.
#
# In iTerm2 Session preferences <Advanced> pane setup Semantic History to:
#
# [Run command...]
#
# in the text input paste the line below:
#
# ~/.emacs.d/iterm-emacsclient +\2 \1
#

if [[ $1 == "+" ]]; then
  shift
fi

/usr/local/bin/emacsclient -q -n -a /usr/local/opt/emacs/Emacs.app/Contents/MacOS/Emacs $1 $2 &
