#+STARTUP: show2levels
* torgeir/.doom.d
:PROPERTIES:
:header-args:emacs-lisp: :lexical t :results silent
:END:

** Lexical scoping everywhere

#+begin_src emacs-lisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+end_src

** Install

First, install doom emacs.

#+begin_src sh :tangle no
git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.emacs.d
~/.emacs.d/bin/doom install
#+end_src

Then the config.

#+begin_src sh :tangle no
cd && git clone git@github.com:torgeir/.emacs.d.git ~/.doom.d
#+end_src

And some terminal shortcuts

#+begin_src sh :tangle no
ln -s ~/.emacs.d/emacsclient ~/bin/e
ln -s ~/.emacs.d/emacsclient-terminal ~/bin/em
#+end_src

** Reload config and doom sync automatically

#+begin_quote
;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!
#+end_quote

That's kinda tedious, tho. Let's automate it

#+begin_src emacs-lisp
(add-to-list 'display-buffer-alist '("\\*t-doom-sync\\*.*" display-buffer-no-window))
(defun t/reload-config ()
  "Used in `after-save-hook'."
  (when (string-equal "~/.doom.d/readme.org" buffer-file-truename)
    (progn
      (org-babel-tangle-file "~/.doom.d/readme.org" "~/.doom.d/config.el")
      (async-shell-command "doom sync" "*t-doom-sync*" "*t-doom-sync*"))))
(add-hook 'after-save-hook #'t/reload-config)
#+end_src

** Recentf

Ignore some of the cached emacs files in recent files

#+begin_src emacs-lisp
(after! recentf
  (add-to-list 'recentf-exclude "\.emacs\.d/\.local"))
#+end_src

** Whoami

#+begin_quote
;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets. It is optional.
#+end_quote

#+begin_src emacs-lisp
(setq user-full-name "Torgeir Thoresen"
      user-mail-address "torgeir.thoresen@gmail.com")
#+end_src

** Macros

A useful macro one for testing stuff out

#+begin_src emacs-lisp
(defmacro comment (&rest ignore)
  nil)

(comment
 (funcall (t/micro-state nil "m" (cmd! (message "1")))))
#+end_src

** Font

#+begin_quote
;; Doom exposes five (optional) variables for controlling fonts in Doom:
;;
;; - `doom-font' -- the primary font to use
;; - `doom-variable-pitch-font' -- a non-monospace font (where applicable)
;; - `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;; - `doom-unicode-font' -- for unicode glyphs
;; - `doom-serif-font' -- for the `fixed-pitch-serif' face
;;
;; See 'C-h v doom-font' for documentation and more examples of what they
;; accept. For example:
;;
#+end_quote

#+begin_quote
JetBrains Mono:pixelsize=16:foundry=JB:weight=medium:slant=normal:width=normal:spacing=100:scalable=true
#+end_quote

#+begin_src emacs-lisp
(setq doom-font
      (font-spec :family "JetBrains Mono" :size 14  :weight 'medium :slant 'normal :width 'normal)
      doom-variable-pitch-font (font-spec :family "JetBrains Mono" :size 14 :weight 'medium :slant 'normal :width 'normal)
      ;; font resize increments
      doom-font-increment 1)
#+end_src

To list available fontsets, do

#+begin_src emacs-lisp
(comment
 (call-interactively 'describe-font))
#+end_src

#+begin_quote
;; If you or Emacs can't find your font, use 'M-x describe-font' to look them
;; up, `M-x eval-region' to execute elisp code, and 'M-x doom/reload-font' to
;; refresh your font settings. If Emacs still can't find your font, it likely
;; wasn't installed correctly. Font issues are rarely Doom issues!
#+end_quote

** Theme

#+begin_quote
;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
#+end_quote

#+begin_src emacs-lisp
(setq doom-theme 'doom-nord)
#+end_src

#+begin_src emacs-lisp
(defun t/cycle-theme ()
  (interactive)
  (if (eq doom-theme 'doom-nord)
      (load-theme 'doom-nord-light)
    (load-theme 'doom-nord)))
(map! :leader "t t" #'t/cycle-theme)
#+end_src

** Editor

#+begin_quote
;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
#+end_quote

#+begin_src emacs-lisp
(setq display-line-numbers-type 'relative)
#+end_src

** Org agenda file setup

#+begin_quote
;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
#+end_quote

#+begin_src emacs-lisp
(setq org-directory (expand-file-name "~/Dropbox/org/")
      org-agenda-files '("~/Dropbox/org")
      org-archive-location "%s_archive.gpg::") ; so files are encrypted automatically
#+end_src

** Doom description

#+begin_quote
;; Whenever you reconfigure a package, make sure to wrap your config in an
;; `after!' block, otherwise Doom's defaults may override your settings. E.g.
;;
;;   (after! PACKAGE
;;     (setq x y))
;;
;; The exceptions to this rule:
;;
;;   - Setting file/directory variables (like `org-directory')
;;   - Setting variables which explicitly tell you to set them before their
;;     package is loaded (see 'C-h v VARIABLE' to look up their documentation).
;;   - Setting doom variables (which start with 'doom-' or '+').
;;
;; Here are some additional functions/macros that will help you configure Doom.
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;; Alternatively, use `C-h o' to look up a symbol (functions, variables, faces,
;; etc).
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.
#+end_quote

** t-defuns

My old collection of more or less usefull defuns.

#+begin_src emacs-lisp
(progn
  (defun t/user-emacs-file (path) (concat (expand-file-name "~/.doom.d/") path))
  (defun t/user-dropbox-folder (path) (expand-file-name (concat "~/Dropbox (Personal)/" path)))
  (defconst is-win IS-WINDOWS)
  (defconst is-cygwin IS-WINDOWS)
  (defconst is-mac IS-MAC)
  (defconst is-linux IS-LINUX)
  (load! "./t-defuns.el"))
#+end_src

** Evil early config

Useful for ~c-e~ followed by ~c-x c-e~ to eval a s-exp.

#+begin_src emacs-lisp
(setq evil-move-beyond-eol t)
#+end_src

** Micro state

A small overlay map that exposes a set of key bindings until you press q, or something else not in the keymap.

#+begin_src emacs-lisp
(defun t/micro-state (quit key fn &rest bindings)
  "Micro state that temporarily overlays a new key map, kinda like hydra"
  (let ((keymap (make-sparse-keymap)))
    (while key
      (bind-key key fn keymap)
      (setq key (pop bindings)
            fn (pop bindings)))
    (lambda ()
      (interactive)
      (let ((exit (set-temporary-overlay-map keymap t (lambda () (when quit (quit-window))))))
        (when quit
          (bind-key "q" (cmd! (funcall exit)) keymap))))))
#+end_src

And one that enters a ~mode~, then turns on the keymap. It turns ~mode~ off again if you hit a key not in the map.

#+begin_src emacs-lisp
(defun t/micro-state-in-mode (mode after key fn &rest bindings)
  "Micro state that toggles mode and temporarily overlays a new key map, kinda like hydra"
  (let ((keymap (make-sparse-keymap)))
    (while key
      (bind-key key fn keymap)
      (setq key (pop bindings)
            fn (pop bindings)))
    (lambda ()
      (interactive)
      (funcall mode)
      (set-temporary-overlay-map keymap t (lambda nil
                                            (funcall mode -1)
                                            (when after (after)))))))
#+end_src

** Keybindings

[[file:~/.emacs.d/modules/editor/evil/config.el::(map! :v "@" #'+evil:apply-macro][Doom editor keybindings]]

#+begin_src emacs-lisp
(map!
 :n "s-0" nil
 "s-0" #'doom/reset-font-size
 "s-+" #'doom/increase-font-size
 "s--" #'doom/decrease-font-size

 "s-?" (lambda () (interactive) (text-scale-increase 1))
 "s-_" (lambda () (interactive) (text-scale-decrease 1))
 "s-=" (lambda () (interactive) (text-scale-set 0))

 "s-d" #'t/split-window-right-and-move-there-dammit
 "s-D" #'t/split-window-below-and-move-there-dammit

 "s-M-<up>" 'evil-window-up
 "s-M-<right>" 'evil-window-right
 "s-M-<down>" 'evil-window-down
 "s-M-<left>" 'evil-window-left

 "M-n" 'forward-paragraph
 "M-p" 'backward-paragraph

 ;; g = global
 :i "C-d" 'delete-char

 "s-k" 'previous-buffer
 "s-j" 'next-buffer
 "s->" 'next-multiframe-window
 "s-<" 'previous-multiframe-window
 "s-<left>" 't/smart-beginning-of-line
 "s-<right>" 'end-of-line

 "C-a" 't/smart-beginning-of-line
 :m "C-e" 'end-of-line

 "s-n" 'make-frame
 "s-s" 'save-buffer

 ;; op -- :leader :desc "Toggle treemacs" "f L" #'+treemacs/toggle
 ;; oO -- :leader :desc "Open folder" "p o" #'t/open-in-desktop

 :leader :desc "Show calendar" "o c" #'calendar
 :leader :desc "Show home" "o h" #'(lambda () (interactive) (find-file (t/user-dropbox-folder "org/home.org.gpg")))
 :leader :desc "Show saga" "o s" #'(lambda () (interactive) (find-file (t/user-dropbox-folder "org/saga.org.gpg")))
 :leader :desc "Open rss" "o S" #'=rss
 :leader :desc "Search the web" "s w" #'consult-web-search
 :leader :desc "Eval and replace" "m e R" #'t/eval-and-replace
 :leader :desc "Toggle transparency" "t T" #'t/transparency
 :leader :desc "Toggle zen" "t d" #'olivetti-mode
 :leader :desc "Debug on error" "t D" #'toggle-debug-on-error

 :leader :desc "Open scratch buffer" "b s" #'doom/open-scratch-buffer
 :mode org-mode
 :leader :desc "Widen" "m s w" 'widen
 )
#+end_src

Prevent drag-stuff-mode from messing things up

#+begin_src emacs-lisp
(map!
 ;; that's irritating
 :after drag-stuff-mode
 :map drag-stuff-mode-map
 "<M-up>"    #'drag-stuff-up ;; messes up org mode
 "<M-down>"  #'drag-stuff-down ;; messes up org mode
 ;; :ni "<M-left>"  #'evil-backward-word-begin
 ;; :ni "<M-right>" #'evil-forward-word-begin
 )
#+end_src

#+RESULTS:

** Rss (elfeed)

#+begin_src emacs-lisp
(after! elfeed
  (setq rmh-elfeed-org-files '("~/Dropbox/org/feeds.org")
        elfeed-search-filter "@2-week-ago +unread")

  (map!
   (:after elfeed
    :map elfeed-search-mode-map
    ;; switcharoo
    :n "gR" #'elfeed-search-update--force
    :n "gr" #'elfeed-search-fetch))

  (add-hook 'elfeed-show-mode-hook #'t/elfeed-show-mode-hook)
  (defun t/elfeed-show-mode-hook ()
    (interactive)
    (let ((map (make-sparse-keymap)))
      (bind-key "n" (lambda ()
                      (interactive)
                      (condition-case nil
                          (scroll-up-command)
                        (error (elfeed-show-next)))) map)
      (bind-key "p" (lambda ()
                      (interactive)
                      (condition-case nil
                          (scroll-down-command)
                        (error (elfeed-show-prev)))) map)
      (bind-key "s" (cmd!
                     (let ((shr-inhibit-images t)) (elfeed-show-refresh))
                     (funcall (t/spray-micro-state))) map)
      (set-temporary-overlay-map map t (lambda () (equal major-mode 'elfeed-show-mode))))))
#+end_src

** Reading

#+begin_src emacs-lisp
(defun t/spray-micro-state (&optional after)
  (t/micro-state-in-mode
   'spray-mode
   after
   "s" 'spray-slower
   "f" 'spray-faster
   "SPC" 'spray-start/stop
   "b" 'spray-backward-word
   "w" 'spray-forward-word
   "<left>" 'spray-backward-word
   "<right>" 'spray-forward-word))

(map! :leader :desc "Toggle spray" "t s" (t/spray-micro-state))

(after! spray
  (setq spray-wpm 720
        spray-height nil)
  (add-hook 'spray-mode-hook #'t/spray-mode-hook)
  (defun t/spray-mode-hook ()
    (setq-local spray-margin-top (truncate (/ (window-height) 2.5)))
    (setq-local spray-margin-left (truncate (/ (window-width) 3.5)))
    (set-face-foreground 'spray-accent-face
                         (face-foreground 'font-lock-keyword-face))))
#+end_src

** Help

#+begin_src emacs-lisp
(map! :leader :n "h h" #'t/describe)
#+end_src

** Smartparens

#+begin_src emacs-lisp
(after! smartparens
  (sp-local-pair 'emacs-lisp-mode "`" "'" :when '(sp-in-docstring-p)))
#+end_src

And some extra for org mode

#+begin_src emacs-lisp
(after! smartparens
  (sp-with-modes 'org-mode
    (sp-local-pair "*" "*" :actions '(insert wrap) :unless '(sp-point-after-word-p sp-point-at-bol-p) :wrap "C-*" :skip-match 'sp--org-skip-asterisk)
    (sp-local-pair "~" "~" :unless '(sp-point-after-word-p) :post-handlers '(("[d1]" "SPC")))
    (sp-local-pair "<" ">" :unless '(sp-point-after-word-p) :post-handlers '(("[d1]" "SPC")))
    (sp-local-pair "=" "=" :unless '(sp-point-after-word-p) :post-handlers '(("[d1]" "SPC")))
    (sp-local-pair "«" "»")))
#+end_src

** Org
*** Org settings

#+begin_src emacs-lisp
(after! org

  (defun t/open-prev-heading ()
    (interactive)
    (let ((was-narrowed (buffer-narrowed-p)))
      (when was-narrowed (widen))
      (when (org-at-heading-p)
        (outline-hide-sublevels (org-outline-level)))
      (org-previous-visible-heading 1)
      (outline-show-subtree)
      (when was-narrowed (org-narrow-to-subtree))))

  (defun t/open-next-heading ()
    (interactive)
    (let ((was-narrowed (buffer-narrowed-p)))
      (when was-narrowed (widen))
      (when (org-at-heading-p)
        (outline-hide-sublevels (org-outline-level)))
      (org-next-visible-heading 1)
      (outline-show-subtree)
      (when was-narrowed (org-narrow-to-subtree))))

  ;; like in normal org, not like in doom
  (map! :after evil-org
        :map evil-org-mode-map
        :ni "C-<return>" #'org-insert-heading-respect-content

        ;; bring back deleting characters from insert in org mode
        :i "C-d" nil

        :map org-mode-map
        :ni "C-c C-p" #'t/open-prev-heading
        :ni "C-c C-n" #'t/open-next-heading)

  ;; Include gpg files in org agenda
  (unless (string-match-p "\\.gpg" org-agenda-file-regexp)
    (setq org-agenda-file-regexp
          (replace-regexp-in-string "\\\\\\.org" "\\\\.org\\\\(\\\\.gpg\\\\)?"
                                    org-agenda-file-regexp)))

  (defun t/org-capture-chrome-link-template (&optional &rest args)
    "Capture current frontmost tab url from chrome."
    (concat "* TODO %? :url:\n\n" (t/grab-chrome-url)))

  (defun t/org-capture-elfeed-link-template (&optional &rest args)
    "Capture open elfeed post with url."
    (concat "* TODO %? :url:%^G\n%i\n" (elfeed-entry-link elfeed-show-entry)))

  (setq org-tags-column -60
        org-support-shift-select t   ; shift can be used to mark multiple lines
        org-special-ctrl-k t         ; don't clear tags, etc
        org-special-ctrl-a/e t       ; don't move past ellipsis on c-e
        org-agenda-skip-scheduled-if-done t
        org-default-notes-file (expand-file-name "~/Dropbox/org/home.org.gpg")
        org-log-done 'time           ; log when todos are completed
        org-log-redeadline 'time     ; log when deadline changes
        org-log-reschedule 'time     ; log when schedule changes
        org-reverse-note-order t     ; newest notes first
        org-return-follows-link t    ; go to http links in browser
        org-todo-keywords '((sequence "TODO(t)" "STARTED(s)" "|" "DONE(d)" "CANCELLED(c)"))))
#+end_src

*** Async source code blocks

Make it possible to use the header argument ~:async true~ for async execution of begin_src code blocks.

#+begin_src emacs-lisp
(after! org
  (require 'ob-async))
#+end_src

*** Hugo capture template

#+begin_src emacs-lisp
(after! org
  (with-eval-after-load 'org-capture
    (defun org-hugo-new-subtree-post-capture-template ()
      "Returns `org-capture' template string for new Hugo post.
See `org-capture-templates' for more information.
https://ox-hugo.scripter.co/doc/org-capture-setup/"
      (let* ((title (read-from-minibuffer "Post Title: "))
             (fname (org-hugo-slug title)))
        (mapconcat #'identity
                   `(,(concat "* TODO " title)
                     ":PROPERTIES:"
                     ,(concat ":EXPORT_FILE_NAME: " fname)
                     ":END:" "%?\n")
                   "\n")))))
#+end_src

**** Capture templates

#+begin_src emacs-lisp
(setq org-capture-templates
      `(("t" "Task" entry (file+olp org-default-notes-file "Tasks") "* TODO %? \n\n%i\n\n" :prepend t :empty-lines-after 1)
        ("s" "Saga" entry (file+olp ,(t/user-dropbox-folder "org/saga.org.gpg") "Tasks") "* TODO %? \n\n%i" :prepend t :empty-lines-after 1)
        ("b" "bekk" entry (file+olp ,(t/user-dropbox-folder "org/bekk.org.gpg") "Tasks") "* TODO %? \n\n%i" :prepend t :empty-lines-after 1)
        ;;("d" "Shared calendar event" entry (file ,(t/user-dropbox-folder "org/gcal/delt.org.gpg")) "* %?\n" :prepent t)
        ("l" "Link" entry (file+olp org-default-notes-file "Tasks") "* TODO %? %^G\n\nLink: %a" :prepend t :empty-lines-after 1)
        ("f" "File" entry (file+olp org-default-notes-file "Tasks") "* TODO %? %^G\n\n%i%a\n\n" :prepend t :empty-lines-after 1)
        ("c" "Chrome location" entry (file+olp org-default-notes-file "Tasks") (function t/org-capture-chrome-link-template) :prepend t :empty-lines-after 1)
        ("e" "Elfeed location" entry (file+olp org-default-notes-file "Tasks") (function t/org-capture-elfeed-link-template) :prepend t :empty-lines-after 1)
        ("p" "Post" entry (file+olp "~/Code/posts/content-org/blog.org" "Drafts") (function org-hugo-new-subtree-post-capture-template))
        ;; ("T" "Personal todo" entry (file+headline +org-capture-todo-file "Inbox") "* %?\n %i\n %a" :prepend t)
        ;; ("j" "Journal" entry (file+olp+datetree +org-capture-journal-file) "* %U %?\n %i\n %a" :prepend t)
        ;; ("n" "Personal notes" entry (file+headline +org-capture-notes-file "Inbox") "* %u %?\n %i\n %a" :prepend t)
        ;; ("p" "Templates for projects") ("pt" "Project-local todo" entry (file+headline +org-capture-project-todo-file "Inbox") "* TODO %?\n %i\n %a" :prepend t)
        ;; ("pn" "Project-local notes" entry (file+headline +org-capture-project-notes-file "Inbox") "* %U %?\n %i\n %a" :prepend t)
        ;; ("pc" "Project-local changelog" entry (file+headline +org-capture-project-changelog-file "Unreleased") "* %U %?\n %i\n %a" :prepend t)
        ;; ("o" "Centralized templates for projects")
        ;; ("ot" "Project todo" entry #'+org-capture-central-project-todo-file "* TODO %?\n %i\n %a" :heading "Tasks" :prepend nil)
        ;; ("on" "Project notes" entry #'+org-capture-central-project-notes-file "* %U %?\n %i\n %a" :heading "Notes" :prepend t)
        ;; ("oc" "Project changelog" entry #'+org-capture-central-project-changelog-file "* %U %?\n %i\n %a" :heading "Changelog" :prepend t)
        ))
#+end_src

** Frame

Show the buffer and the file

#+begin_src emacs-lisp
(setq frame-title-format "%b (%f)")
#+end_src

** Eww

An elisp web browser.

*** Lookup

Make ~SPC s o~ open in eww first, then use ~&~ to go to the default browser if needed.

#+begin_src emacs-lisp
(setq +lookup-open-url-fn #'eww)
#+end_src

*** Popup size

#+begin_src emacs-lisp
(after! evil
  ;; the original way
  ;;(setf (alist-get 'size (display-buffer-assq-regexp "*eww*" display-buffer-alist nil)) 0.8)
  ;; the doom way
  (set-popup-rule! "^\\*eww*" :side 'bottom :size 0.8))
#+end_src

*** Readability

Enter readable mode automatically, normally available from pressing ~R~ in eww mode.

#+begin_src emacs-lisp
(add-hook 'eww-after-render-hook 'eww-readable)
#+end_src

Eww functions that directly enter the eww readability mode after loading a given url

#+BEGIN_SRC emacs-lisp
(defun t/eww-readable-after-render (status url buffer fn)
  (eww-render status url nil buffer)
  (switch-to-buffer buffer)
  (eww-readable)
  (let ((content (buffer-substring-no-properties (point-min) (point-max))))
    (read-only-mode 0)
    (erase-buffer)
    (insert content)
    (beginning-of-buffer)
    (toggle-truncate-lines -1)
    (when fn (funcall fn))))

(defun t/eww-readable (url &optional fn)
  (interactive "sEnter URL: ")
  (let ((buffer (get-buffer-create "*eww*")))
    (with-current-buffer buffer
      (autoload 'eww-setup-buffer "eww")
      (eww-setup-buffer)
      (url-retrieve url 't/eww-readable-after-render (list url buffer fn)))))
#+END_SRC

*** Images and wrap long lines

#+BEGIN_SRC emacs-lisp
(after! shr
  ;; don't truncate lines in
  (defun shr-fill-text (text) text)
  (defun shr-fill-lines (start end) nil)
  (defun shr-fill-line () nil)

  ;; not too large images
  (setq shr-use-fonts nil
        shr-max-image-proportion 0.6
        shr-ignore-cache t))
#+END_SRC

*** TODO Open from chrome

Opens the frontmost chrome url in eww.

This does not work atm, ~(void-function org-mac-chrome-get-frontmost-url)~.

#+BEGIN_SRC emacs-lisp
(comment defun t/visit-frontmost-chrome-url-in-eww ()
  "Visit the front-most url of chrome in eww."
  (interactive)
  (eww (t/grab-chrome-url)))
#+END_SRC

*** Hook and keybindings

Some useful eww keybindings

#+BEGIN_SRC emacs-lisp
(after! eww
  (defun t/eww-hook ()
    (map!
     :map evil-normal-state-local-map
     "q" 'quit-window
     "S-TAB" 'shr-previous-link
     "TAB" 'shr-next-link
     "R" 'eww-readable
     "M-p" 'backward-paragraph
     "M-n" 'forward-paragraph
     "s-l" 'eww
     "s" (t/spray-micro-state))))
(add-hook 'eww-mode-hook #'t/eww-hook)
#+END_SRC

** Dired

#+begin_src emacs-lisp
(after! dired
  (add-hook 'dired-mode-hook 'dired-hide-details-mode))
#+end_src

** Nrk.no

A custom function to fetch a clean view of the current news from nrk.no

#+BEGIN_SRC emacs-lisp :results silent
(defun t/clean-nrk-buffer ()
  (flush-lines "^$")
  ;; clean up lines beginning with dates, e.g. 20. sept...
  (beginning-of-buffer)
  (flush-lines "^[0-9][0-9]\.")

  ;; clean up lines beginning with -
  (beginning-of-buffer)
  (t/cleanup-buffer-whitespace-and-indent)
  (while (re-search-forward "*" nil t)
    ;; kill lines with dates, all these news are new
    (when (string-match-p "^* [0-9][0-9]\." (thing-at-point 'line))
      (kill-line) (forward-line) (join-line))
    ;; change * to -
    (replace-match "\n-")
    ;; highlight the line
    (add-text-properties (point-at-bol) (point-at-eol) '(face outline-4)))

  (beginning-of-buffer)

  ;; kill more lines with dates
  (while (re-search-forward "^[0-9][0-9]\." nil t)
    (when (string-match-p "^[0-9][0-9]\. [jfmasond]" (thing-at-point 'line))
      (beginning-of-line) (kill-line) (forward-line) (join-line)))

  ;; remove leading line
  (beginning-of-buffer)
  (kill-line)

  ;;(darkroom-mode)
  (read-only-mode)
  (funcall (t/micro-state (t/prefix-arg-universal?)
                          "n" (cmd! nil
                                        (evil-search "^-" t t)
                                        (evil-ex-nohighlight)
                                        (recenter nil))
                          "p" (cmd! nil
                                        (evil-search "^-" nil t)
                                        (evil-ex-nohighlight)
                                        (recenter nil))
                          "s" (t/spray-micro-state))))
#+END_SRC

Bind it to ~SPC o n~

#+begin_src emacs-lisp
(map!
 :leader
 (:prefix ("o" . "open")
  :desc "Show nrk.no" "n" (cmd! (t/eww-readable "https://www.nrk.no/nyheter/" 't/clean-nrk-buffer))))
#+end_src

** Ediff

#+begin_src emacs-lisp
;; (setq ediff-window-setup-function 'ediff-setup-windows-plain)
#+end_src

** Emacs lisp

#+begin_src emacs-lisp
(after! evil
  (add-hook 'emacs-lisp-mode-hook #'evil-cleverparens-mode))
#+end_src

** Calendar

Weeks on start on monday in Norway, and weeks have numbers.

#+begin_src emacs-lisp
(after! calendar
  (setq calendar-week-start-day 1
        calendar-intermonth-text
        '(propertize (format "%2d" (car
                                    (calendar-iso-from-absolute
                                     (calendar-absolute-from-gregorian
                                      (list month day year)))))
                     'font-lock-face 'calendar-iso-week-face))
  (copy-face font-lock-constant-face 'calendar-iso-week-face)
  (copy-face 'default 'calendar-iso-week-header-face))
#+end_src

** Server mode

Emacs server setup. This name is used from ~/.emacs.d/emacsclient~ and ~/.emacs.d/emacsclient~, linked as ~e~ and ~em~ on the command line, to target the running emacs server instance.

#+begin_src emacs-lisp
(setq server-name "torgemacs")
#+end_src

I also use this from Alfred, as a quick way of capturing from anywhere on os x.

#+begin_src sh :tangle no
/usr/local/bin/emacsclient -s torgemacs -e '(progn (select-frame-set-input-focus (selected-frame)) (org-capture))'
#+end_src

** Which key

Don't bother waiting

#+begin_src emacs-lisp
(setq which-key-idle-delay 0.1)
#+end_src

** Evil registers

Some macros I once used.

This one makes camelCaseWords into to snake_case_words. Run it with ~@c~

#+begin_src emacs-lisp
(evil-set-register ?c [?: ?s ?/ ?\\ ?\( ?\[ ?a ?- ?z ?0 ?- ?9 ?\] ?\\ ?\) ?\\ ?\( ?\[ ?A ?- ?Z ?0 ?- ?9 ?\] ?\\ ?\) ?/ ?\\ ?1 ?_ ?\\ ?l ?\\ ?2 ?/ ?g])
#+end_src

** Distraction free, writeroom, olivetti

#+begin_src emacs-lisp
(after! olivetti
  (setq olivetti-style t
        olivetti-minimum-body-width 40)
  (defun olivetti-turn-off-line-numbers ()
    (setq display-line-numbers nil
          indicate-empty-lines nil
          ;; and set max width
          olivetti-body-width (if (< (frame-width (selected-frame)) 300) 0.6 0.5)))
  (defun olivetti-bring-back-line-numbers ()
    (setq display-line-numbers 'relative
          indicate-empty-lines t))
  (add-hook 'olivetti-mode-on-hook #'olivetti-turn-off-line-numbers)
  (add-hook 'olivetti-mode-off-hook #'olivetti-bring-back-line-numbers))
#+end_src

** Magit and Forge

#+begin_src emacs-lisp
(after! magit
  (setq magit-fetch-arguments '("--prune")
        magit-rebase-arguments '("--interactive")
        magit-log-arguments '("--graph" "--color" "--decorate" "-n256")
        git-commit-summary-max-length 72 ;; like github
        magit-display-buffer-function 'magit-display-buffer-fullcolumn-most-v1)
  (set-popup-rule! "^\\magit-log" :side 'right :size 0.5)
  (set-popup-rule! "^\\magit-revision" :side 'right :size 0.5))
#+end_src

Extend leader map with ~gn~ and ~gN~, for navigating hunks, the g] and g[ bindings never made sense to me. And ~gca~ for amending.

#+begin_src emacs-lisp
(map!
 :leader
 (:prefix-map ("g" . "git")
  (:when (featurep! :ui vc-gutter)
   :desc "Jump to next hunk"     "n" #'git-gutter:next-hunk
   :desc "Jump to previous hunk" "N" #'git-gutter:previous-hunk)
  (:when (featurep! :tools magit)
   (:prefix ("c" . "create")
    :desc "Ammend"                    "a"   #'magit-commit-amend))))
#+end_src

** Embark

#+begin_src emacs-lisp
(map!
 :g "C-," #'embark-act ; global
 :map org-mode-map "C-," #'embark-act
 :map minibuffer-mode-map "C-," #'embark-act)
;;(add-hook 'completion-list-mode-hook #'consult-preview-at-point-mode)
#+end_src

Embark improve prefix help commands, e.g. ~C-c C-h~, by showing auto complete.

** Multiple cursors

#+begin_src emacs-lisp
(after! evil
  (defun t/mc-skip-prev ()
    (interactive)
    (evil-multiedit-toggle-or-restrict-region)
    (evil-multiedit-match-and-prev))

  (defun t/mc-skip-next ()
    (interactive)
    (evil-multiedit-toggle-or-restrict-region)
    (evil-multiedit-match-and-next)))
#+end_src

Make cursor follow matches so ~m-n~ or ~m-p~ can be used to skip matches easily, depending on what direction you are moving in.

#+begin_src emacs-lisp
(after! evil
  (setq evil-multiedit-follow-matches t)
  (map!
   :after evil
   :mode evil-multiedit-mode
   ;; for some reason m-j does not work, use m-n and m-p instead
   :n "M-n"   #'t/mc-skip-next
   :n "M-p"   #'t/mc-skip-prev))
#+end_src

Multiedit calls iedit which is missing all-caps in emacs 29.

#+begin_src elisp
(when (version< "29.0" emacs-version)
  (defun all-caps (smtn)
    (upper smtn)))
#+end_src

** Site lisp

#+begin_src emacs-lisp
(after! org
  (use-package! ox-gfm :load-path "site-lisp/ox-gfm/"))
#+end_src

#+begin_src emacs-lisp
(use-package! consult-async :load-path "site-lisp/consult-async/")
#+end_src

#+begin_src emacs-lisp
(comment
 (message "result: %s"
          (consult-t-async (lambda (action fn)
                             (t/async-shell-command
                              "file listing"
                              (concat "ls -l " action)
                              (lambda (p code res)
                                (funcall fn res)))))))
#+end_src

** Terminal from everywhere with s-return
:PROPERTIES:
:ID:       607b5e84-af21-4da9-80a9-8a44c2d12f0b
:END:

Make super+enter create a vterm terminal window inside emacs

#+begin_src emacs-lisp
(map! :gn [s-return] #'+vterm/here)
#+end_src

Goes great with [[file:~/dotfiles/skhdrc::cmd - return \[][these lines from ~/.skhdrc]], that make super+enter create a terminal from other apps

** Twitter

#+begin_src emacs-lisp
(after! twittering-mode
  (setq twittering-initial-timeline-spec-string '(":mentions" ":home")
        twittering-use-master-password t))
#+end_src

** Info mode

#+begin_src emacs-lisp
(after! info-mode
  (map!
   :map Info-mode-map
   "M-n" #'forward-paragraph
   "M-p" #'backward-paragraph))
#+end_src

** Stuff to test

*** Skeleton mode instead of yasnippet?

https://www.emacswiki.org/emacs/SkeletonMode

#+begin_src elisp
(comment
 (define-skeleton skel-defun
   "Insert a defun template."
   "Name: "
   "(defun " str " (" @ - ")" \n
   "(" @ _ ")" \n)

 (defvar *skeleton-markers* nil
   "Markers for locations saved in skeleton-positions")

 (add-hook 'skeleton-end-hook 'skeleton-make-markers)

 (defun skeleton-make-markers ()
   (while *skeleton-markers*
     (set-marker (pop *skeleton-markers*) nil))
   (setq *skeleton-markers*
         (mapcar 'copy-marker (reverse skeleton-positions))))

 (defun skeleton-next-position (&optional reverse)
   "Jump to next position in skeleton.
         REVERSE - Jump to previous position in skeleton"
   (interactive "P")
   (let* ((positions (mapcar 'marker-position *skeleton-markers*))
          (positions (if reverse (reverse positions) positions))
          (comp (if reverse '> '<))
          pos)
     (when positions
       (if (catch 'break
             (while (setq pos (pop positions))
               (when (funcall comp (point) pos)
                 (throw 'break t))))
           (goto-char pos)
         (goto-char (marker-position
                     (car *skeleton-markers*))))))))
#+end_src

*** Sticky buffer mode

Useful e.g. to make dired act like a directory tree sidebar

#+begin_src emacs-lisp :results silent
(define-minor-mode sticky-buffer-mode
  "Make the current window always display this buffer."
  nil " sticky" nil
  (set-window-dedicated-p (selected-window) sticky-buffer-mode)
  (setq window-size-fixed (if sticky-buffer-mode 'width nil)))
#+end_src

*** gh run watch

#+begin_src emacs-lisp :results silent
(defun t/gha ()
  (interactive)
  (multi-vterm)
  (term-send-raw-string "gh run watch\C-m"))
#+end_src

*** xref jump to selection

#+begin_src emacs-lisp
(comment

 (progn

   (require 'xref)
   (let ((l (xref-location-marker
             (xref-make-file-location
              (t/user-emacs-file "test-files/index.js")
              27
              11))))
     (xref--show-pos-in-buf l (marker-buffer l))))
 )
#+end_src

